branch-defaults:
  main:
    environment: drug-classification-env
global:
  application_name: drug-classification
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
